"""Welcome screen setup command."""

import click
import subprocess
import sys


@click.command()
@click.argument('target', required=True)
@click.option(
    '--text',
    default='',
    help='Custom ASCII art text (default: uses hostname in uppercase)'
)
@click.option(
    '--font',
    default='slant',
    help='figlet font: standard, slant, banner, big, block, bubble, digital, lean, small'
)
@click.option(
    '--color',
    default='cyan',
    type=click.Choice(['red', 'green', 'yellow', 'blue', 'magenta', 'cyan', 'white']),
    help='Color for ASCII art banner'
)
def welcome(target, text, font, color):
    """
    Set up Ubuntu welcome screen (MOTD) on a remote server.

    TARGET is the SSH destination (e.g., root@192.168.1.41).

    Installs figlet and configures a custom SSH login banner with
    ASCII art and system information.

    \b
    Examples:
        nccli welcome root@192.168.1.41
        nccli welcome root@192.168.1.41 --text "PROD-API"
        nccli welcome root@192.168.1.41 --text "DEV-01" --font big --color green

    \b
    The --text flag sets the large ASCII art banner text shown at login.
    If omitted, the server's hostname is used automatically.
    """
    color_codes = {
        'red': '31',
        'green': '32',
        'yellow': '33',
        'blue': '34',
        'magenta': '35',
        'cyan': '36',
        'white': '37',
    }
    color_code = color_codes.get(color, '36')

    click.echo(f"Setting up welcome screen on {target}...")
    if text:
        click.echo(f"  Banner text: {text}")
    else:
        click.echo("  Banner text: (hostname)")
    click.echo(f"  Font: {font}, Color: {color}")

    # Build the MOTD script - matching the user's expected format
    motd_script = f'''#!/bin/bash
#
# Custom Welcome Screen
# Generated by nccli welcome
#

# Configuration
WELCOME_TEXT="{text}"
ASCII_FONT="{font}"
COLOR_CODE="{color_code}"

# Use hostname if WELCOME_TEXT is empty
if [ -z "$WELCOME_TEXT" ]; then
    WELCOME_TEXT=$(hostname | tr '[:lower:]' '[:upper:]')
fi

# Print ASCII art with color
echo ""
echo -e "\\033[1;${{COLOR_CODE}}m"
figlet -f "$ASCII_FONT" "$WELCOME_TEXT" 2>/dev/null || echo "$WELCOME_TEXT"
echo -e "\\033[0m"

# Print welcome message and system info
echo ""
echo "Welcome to $(hostname)"
echo ""
echo "System Information:"
echo "  - IP Address: $(hostname -I | awk '{{print $1}}')"
echo "  - CPU Cores:  $(nproc)"
echo "  - Uptime:     $(uptime -p)"
echo "  - Memory:     $(free -h | awk '/^Mem:/ {{print $3 "/" $2}}')"
echo "  - Disk:       $(df -h / | awk 'NR==2 {{print $3 "/" $2 " (" $5 " used)"}}')"
echo "  - Load:       $(cat /proc/loadavg | awk '{{print $1, $2, $3}}')"
echo ""
'''

    # Build the remote setup script
    remote_script = f'''set -e

echo "Installing figlet..."
apt-get update -qq
apt-get install -y -qq figlet > /dev/null 2>&1
echo "figlet installed"

# Create custom MOTD script
cat > /etc/update-motd.d/00-custom-welcome << 'MOTD_EOF'
{motd_script}
MOTD_EOF

chmod +x /etc/update-motd.d/00-custom-welcome

# Disable some default MOTD scripts that may clutter the output
for f in /etc/update-motd.d/10-help-text /etc/update-motd.d/50-motd-news /etc/update-motd.d/80-livepatch; do
    if [ -f "$f" ]; then
        chmod -x "$f" 2>/dev/null || true
    fi
done

echo ""
echo "Testing welcome screen..."
echo "========================="
run-parts /etc/update-motd.d/ 2>/dev/null || /etc/update-motd.d/00-custom-welcome
'''

    try:
        result = subprocess.run(
            ['ssh', '-o', 'ConnectTimeout=10', target, 'bash'],
            input=remote_script,
            text=True,
            capture_output=True,
            timeout=120,
        )

        if result.returncode != 0:
            click.echo(f"Error: {result.stderr}", err=True)
            sys.exit(1)

        click.echo(result.stdout)
        click.echo()
        click.secho("Welcome screen setup complete!", fg='green')
        click.echo(f"To test, SSH into the server: ssh {target}")
        click.echo("To edit, modify: /etc/update-motd.d/00-custom-welcome")

    except subprocess.TimeoutExpired:
        click.echo("Error: SSH connection timed out", err=True)
        sys.exit(1)
    except FileNotFoundError:
        click.echo("Error: ssh command not found", err=True)
        sys.exit(1)
    except Exception as e:
        click.echo(f"Error: {e}", err=True)
        sys.exit(1)
