#!/bin/bash
#
# Ubuntu Welcome Screen Setup Script
# Creates a custom ASCII art welcome screen (MOTD) for Ubuntu Linux
#
# Usage: ./setup-welcome-screen.sh [user@host]
# Example: ./setup-welcome-screen.sh root@192.168.1.41
#

set -e

# =============================================================================
# CONFIGURATION - EDIT THESE VALUES
# =============================================================================

# The text to display as ASCII art (leave empty to use hostname)
WELCOME_TEXT=""

# ASCII art font (run 'figlet -l' on target to see available fonts)
# Popular fonts: standard, slant, banner, big, block, bubble, digital, lean
ASCII_FONT="slant"

# Welcome message lines (displayed below ASCII art)
# Edit these to customize your welcome message
WELCOME_MESSAGE=(
    ""
    "Welcome to \$(hostname)"
    ""
    "System Information:"
    "  - IP Address: \$(hostname -I | awk '{print \$1}')"
    "  - Uptime: \$(uptime -p)"
    "  - Memory: \$(free -h | awk '/^Mem:/ {print \$3 \"/\" \$2}')"
    "  - Disk: \$(df -h / | awk 'NR==2 {print \$3 \"/\" \$2 \" (\" \$5 \" used)\"}')"
    "  - Load: \$(cat /proc/loadavg | awk '{print \$1, \$2, \$3}')"
    ""
    "Last login: \$(last -1 -R \$USER 2>/dev/null | head -1 | awk '{print \$3, \$4, \$5, \$6}' || echo 'N/A')"
    ""
)

# Color for ASCII art (options: red, green, yellow, blue, magenta, cyan, white)
ASCII_COLOR="cyan"

# Show system info (true/false)
SHOW_SYSTEM_INFO=true

# =============================================================================
# END OF CONFIGURATION
# =============================================================================

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

log_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# Get target server from argument or prompt
TARGET_SERVER="$1"

if [ -z "$TARGET_SERVER" ]; then
    echo ""
    echo "Ubuntu Welcome Screen Setup"
    echo "============================"
    echo ""
    read -p "Enter target server (e.g., root@192.168.1.41): " TARGET_SERVER
fi

if [ -z "$TARGET_SERVER" ]; then
    log_error "No target server specified"
    exit 1
fi

echo ""
log_info "Setting up welcome screen on $TARGET_SERVER..."
echo ""

# Map color name to ANSI code
get_color_code() {
    case "$1" in
        red)     echo "31" ;;
        green)   echo "32" ;;
        yellow)  echo "33" ;;
        blue)    echo "34" ;;
        magenta) echo "35" ;;
        cyan)    echo "36" ;;
        white)   echo "37" ;;
        *)       echo "36" ;;  # default cyan
    esac
}

COLOR_CODE=$(get_color_code "$ASCII_COLOR")

# Build the welcome message script content
build_welcome_message() {
    local msg=""
    for line in "${WELCOME_MESSAGE[@]}"; do
        msg+="echo \"$line\"\n"
    done
    echo -e "$msg"
}

WELCOME_MSG_SCRIPT=$(build_welcome_message)

# Create the MOTD script on remote server
ssh "$TARGET_SERVER" bash << REMOTE_SCRIPT
set -e

echo "Installing figlet..."
apt-get update -qq
apt-get install -y -qq figlet > /dev/null 2>&1
echo "figlet installed"

# Disable default MOTD scripts (optional - uncomment to disable)
# chmod -x /etc/update-motd.d/* 2>/dev/null || true

# Create custom MOTD script
cat > /etc/update-motd.d/00-custom-welcome << 'MOTD_EOF'
#!/bin/bash
#
# Custom Welcome Screen
# Generated by setup-welcome-screen.sh
#

# Configuration
WELCOME_TEXT="${WELCOME_TEXT}"
ASCII_FONT="${ASCII_FONT}"
COLOR_CODE="${COLOR_CODE}"

# Use hostname if WELCOME_TEXT is empty
if [ -z "\$WELCOME_TEXT" ]; then
    WELCOME_TEXT=\$(hostname | tr '[:lower:]' '[:upper:]')
fi

# Print ASCII art with color
echo ""
echo -e "\033[1;\${COLOR_CODE}m"
figlet -f "\$ASCII_FONT" "\$WELCOME_TEXT" 2>/dev/null || echo "\$WELCOME_TEXT"
echo -e "\033[0m"

# Print welcome message
$WELCOME_MSG_SCRIPT
MOTD_EOF

chmod +x /etc/update-motd.d/00-custom-welcome

# Make it the first script to run
if [ -f /etc/update-motd.d/10-help-text ]; then
    chmod -x /etc/update-motd.d/10-help-text 2>/dev/null || true
fi

echo ""
echo "Testing welcome screen..."
echo "========================="
run-parts /etc/update-motd.d/ 2>/dev/null || /etc/update-motd.d/00-custom-welcome

REMOTE_SCRIPT

echo ""
log_success "Welcome screen setup complete on $TARGET_SERVER"
echo ""
log_info "To test, SSH into the server: ssh $TARGET_SERVER"
log_info "To edit, modify: /etc/update-motd.d/00-custom-welcome"
echo ""
